name: ${project.name}
main: jp.azisaba.lgw.rankingdisplayer.RankingDisplayer
version: ${project.version}
authors: [siloneco, sysnote8main]
api-version: 1.16
description: "Display kill ranking plugin"
depend: ["PlayerSettings", "KDStatusReloaded", "DecentHolograms"]
commands:
  ranking:
    usage: /ranking
    permission: rankingdisplayer.command.ranking
  rankingholo:
    usage: /rankingholo <place|remove|remove-all|list>
    permission: rankingdisplayer.command.rankingholo
  rankingdisplayer:
    usage: /rankingdisplayer <reload>
    permission: rankingdisplayer.command.rankingdisplayer
permissions:
  rankingdisplayer.command.ranking:
    default: true