name: ${project.name}
main: jp.azisaba.lgw.rankingdisplayer.RankingDisplayer
version: ${project.version}
author: siloneco
api-version: 1.16
description: "Display kill ranking plugin"
depend: ["PlayerSettings", "KDStatusReloaded", "DecentHolograms"]
commands:
  ranking:
    usage: /ranking
    permission: rankingdisplayer.command.ranking
permissions:
  rankingdisplayer.command.ranking:
    default: true