name: '${name}'
main: net.azisaba.rankingdisplayer.RankingDisplayer
version: '${version}'
authors: [siloneco, sysnote8main]
api-version: 1.16
description: '${description}'
website: '${websiteUrl}'
depend: ["PlayerSettings", "KDStatusReloaded", "DecentHolograms", "PlaceholderAPI"]
commands:
  ranking:
    usage: /ranking
    permission: rankingdisplayer.command.ranking
  rankingholo:
    usage: /rankingholo <place|remove|remove-all|list>
    permission: rankingdisplayer.command.rankingholo
  rankingdisplayer:
    usage: /rankingdisplayer <reload>
    permission: rankingdisplayer.command.rankingdisplayer
permissions:
  rankingdisplayer.command.ranking:
    default: true
