---
name: Build Test
"on": [push]

jobs:
  build-test:
    name: Build with Java 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "adopt"
          cache: "maven"
      - run: java -version
      - run: mvn --version
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v3.1.1
        with:
          step: restore
      - run: mvn -B package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: /home/runner/work/RankingDisplayer/RankingDisplayer/target/
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v3.1.1
        with:
          step: save
